name: '🧑‍🏭'
on: [ push, pull_request ]
permissions:
  contents: write
jobs:

  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - run: go test -v -vet='all' ./...
